### ISSUE TITLE
Error while trying to build pothos on El Capitan

### ISSUE THREAD

**Issue by fdb** [pothosware/homebrew-pothos#1]
Executing the listed install commands fail with a make error. Here are the commands I executed:

    brew tap pothosware/homebrew-pothos
    brew update
    brew install --HEAD pothos

Here are the error commands (as generated by `brew gist-logs pothos`): https://gist.github.com/anonymous/ba2b140fb926faaed805

If you need any more info to debug this issue, please let me know.

**Comment by audiofilter** [comment]
It's hard to see the issue exactly from the log files, but i just done
brew reinstall --HEAD pothos
without issue
...
/usr/local/lib/python2.7/site-packages/PothosTestBlocks/SimpleSigSlots.py
/usr/local/lib/python2.7/site-packages/PothosTestBlocks/__init__.py
Warning: Could not fix libpython2.7.dylib in /usr/local/Cellar/pothos/HEAD/lib/Pothos/modules/proxy/environment/libPythonSupport.so
Warning: Could not fix libpython2.7.dylib in /usr/local/Cellar/pothos/HEAD/lib/python2.7/site-packages/Pothos/PothosModule.so
==> Summary
🍺  /usr/local/Cellar/pothos/HEAD: 2162 files, 60M, built in 3.7 minutes

**Comment by guruofquality** [comment]
Java toolkit doesnt do anything yet, and it likes to cause some inconsistent headache. For the next release its moving out of the main build. Disabled java: https://github.com/pothosware/homebrew-pothos/commit/53dd99d3b8dc64049ccb179706351137a6d4792f

```
[ 54%] Linking CXX shared module libJavaSupport.so
cd /tmp/pothos20151101-97927-veej8d/build/java && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/JavaSupport.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++   -std=c++0x -Wc++11-extensions -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -bundle -Wl,-headerpad_max_install_names  -flat_namespace -o libJavaSupport.so CMakeFiles/JavaSupport.dir/JavaProxy.cpp.o CMakeFiles/JavaSupport.dir/JavaConvert.cpp.o CMakeFiles/JavaSupport.dir/JavaHelper.cpp.o CMakeFiles/JavaSupport.dir/JavaHandle.cpp.o CMakeFiles/JavaSupport.dir/TestJava.cpp.o CMakeFiles/JavaSupport.dir/Containers.cpp.o ../library/lib/libPothos.0.3.0.dylib ../serialization/libPothosSerialization.0.dylib /usr/local/lib/libPocoUtil.31.dylib /usr/local/lib/libPocoJSON.31.dylib /usr/local/lib/libPocoXML.31.dylib /usr/local/lib/libPocoNet.31.dylib /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libjawt.dylib /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/server/libjvm.dylib /usr/local/lib/libPocoFoundation.31.dylib -ldl -framework CoreFoundation -Wl,-rpath,/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib -Wl,-rpath,/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/server 
cd /tmp/pothos20151101-97927-veej8d/build && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/pothos20151101-97927-veej8d /tmp/pothos20151101-97927-veej8d/widgets /tmp/pothos20151101-97927-veej8d/build /tmp/pothos20151101-97927-veej8d/build/widgets /tmp/pothos20151101-97927-veej8d/build/widgets/CMakeFiles/ControlWidgets.dir/DependInfo.cmake --color=
ld: file not found: @rpath/libawt_lwawt.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

@fdb So let me know if things build now.

It might be worthwhile to disable a whole bunch of toolkits and make more formulas for building the tookits stand-alone. That way people get to pick and choose, graphics are optional...

**Comment by fdb** [comment]
Yay, it works now! Thanks!

    brew install --HEAD pothos
    ==> Installing pothos from pothosware/homebrew-pothos
    ==> Cloning https://github.com/pothosware/pothos.git
    Updating /Library/Caches/Homebrew/pothos--git
    ==> Checking out branch master
    ==> cmake .. -DENABLE_JAVA=OFF -DPOTHOS_ROOT='/usr/local' -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/
    ==> make install
    🍺  /usr/local/Cellar/pothos/HEAD: 2162 files, 60M, built in 2.9 minutes
