### ISSUE TITLE
pothosgui: brew linkapps is deprecated

### ISSUE THREAD

**Issue by rambo** [pothosware/homebrew-pothos#10]
> Warning: `brew linkapps` has been deprecated and will eventually be removed!
> 
> Unfortunately `brew linkapps` cannot behave nicely with e.g. Spotlight using
> either aliases or symlinks and Homebrew formulae do not build "proper" `.app`
> bundles that can be relocated. Instead, please consider using `brew cask` and
> migrate formulae using `.app`s to casks.

<https://github.com/pothosware/homebrew-pothos/wiki> tells to use `linkapps`

**Comment by guruofquality** [comment]
I'm not entirely sure what I am supposed to do with cask, but linkapps is just making a symlink. We can replace it with: `ln -sf ~/Applications/PothosGui.app /usr/local/opt/pothosgui/PothosGui.app` Then there will be a shortcut in Home->Applications (for example)

**Comment by guruofquality** [comment]
removed linkapps from wiki page, I suggested the symlink. If this can be done better, suggestions are appreciated. Ty
