### ISSUE TITLE
brew install pothossdr make install error

### ISSUE THREAD

**Issue by TranquilTravis** [pothosware/homebrew-pothos#11]
I try to install pothossdr on mac os 10.12.4, following the guide, but I get "make install" error. Can you Help? thx.

run: brew install pothossdr

I get the following output:
==> Installing pothossdr from pothosware/pothos
==> Downloading https://github.com/pothosware/pothos-sdr/archive/pothos-sdr-0.4.
Already downloaded: /Users/xxx/Library/Caches/Homebrew/pothossdr-0.4.3.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make install
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/pothossdr/02.make:
2017-06-08 18:15:09 -0400

make
install

make: *** No rule to make target `install'.  Stop.

Travis

**Comment by guruofquality** [comment]
Thats a really strange issue. Can you try `brew install pothossdr --verbose` and post the output?

**Comment by TranquilTravis** [comment]
**# In between, I got these warning:**

warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.landscape.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
warning: no previously-included files found matching 'appveyor.yml'
no previously-included directories found matching '.github'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'

**# And there are some useful outputs:**

==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: http://docs.brew.sh/Homebrew-and-Python.html
==> Summary
🍺  /usr/local/Cellar/python/2.7.13: 3,526 files, 48MB
==> Installing pothosware/pothos/pothossdr
==> Downloading https://github.com/pothosware/pothos-sdr/archive/pothos-sdr-0.4.3.tar.gz
Already downloaded: /Users/dongqi/Library/Caches/Homebrew/pothossdr-0.4.3.tar.gz
==> Verifying pothossdr-0.4.3.tar.gz checksum
tar xzf /Users/dongqi/Library/Caches/Homebrew/pothossdr-0.4.3.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/pothossdr/0.4.3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Poco_VERSION: 1.7.8
-- Poco_INCLUDE_DIRS:
-- Poco_LIBRARIES: Poco::Foundation;Poco::Util;Poco::JSON;Poco::XML;Poco::Net
CMake Warning at CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "SoapySDR" with any
  of the following names:

    SoapySDRConfig.cmake
    soapysdr-config.cmake

  Add the installation prefix of "SoapySDR" to CMAKE_PREFIX_PATH or set
  "SoapySDR_DIR" to a directory containing one of the above files.  If
  "SoapySDR" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at CMakeLists.txt:23 (message):
  Pothos SDR blocks require SoapySDR, skipping...


-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_FLAGS_RELEASE


-- Build files have been written to: /tmp/pothossdr-20170609-26117-1loqqu6/pothos-sdr-pothos-sdr-0.4.3/build
==> make install
make: *** No rule to make target `install'.  Stop.

==> Formula
Tap: pothosware/pothos
Path: /usr/local/Homebrew/Library/Taps/pothosware/homebrew-pothos/pothossdr.rb
==> Configuration
HOMEBREW_VERSION: 1.2.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 54e01d76db34a3a649c79b189873bfd0a52dbc9f
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2e3bec1594bd0bba12725e49a537754ad87896cb
Core tap last commit: 46 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /Users/dongqi/anaconda3/bin/python => /Users/dongqi/anaconda3/bin/python3.5
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_51
macOS: 10.12.4-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.8 => /opt/X11
MacPorts/Fink: /opt/local/bin/port
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/muparserx/lib/pkgconfig:/usr/local/opt/pothos/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/python/lib/pkgconfig:/usr/local/opt/soapysdr/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/cmake/bin:/usr/local/opt/openssl/bin:/usr/local/opt/poco/bin:/usr/local/opt/pothos/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/python/bin:/usr/local/opt/soapysdr/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: pothosware/pothos/pothossdr 0.4.3 did not build
Logs:
     /Users/dongqi/Library/Logs/Homebrew/pothossdr/00.options.out
     /Users/dongqi/Library/Logs/Homebrew/pothossdr/01.cmake
     /Users/dongqi/Library/Logs/Homebrew/pothossdr/01.cmake.cc
     /Users/dongqi/Library/Logs/Homebrew/pothossdr/02.make
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/pothosware/homebrew-pothos/issues

These open issues may also help:
brew install pothossdr make install error https://github.com/pothosware/homebrew-pothos/issues/11

Error: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

I suspect there could be my python problem, some dependencies linked to wrong python file. But, I  can't figure out the exact reason.

**Comment by guruofquality** [comment]
> Could not find a package configuration file provided by "SoapySDR" with any

Not sure why it cant find soapysdr development files, but this is definitely the cause. Try brew reinstalling soapysdr

**Comment by TranquilTravis** [comment]
Hi, I solved this problem by completely remove home-brew and reinstall it. Then everything installed perfectly. I still not sure which part goes wrong (although I think it's python problem); it could be dependency point to wrong file, or sys.path not correct. Anyway, I am tired of tracking down the exact reason, and decided to have a fresh start. It might not be the best way, but it worked by now. Thanks for your help.

**Comment by guruofquality** [comment]
Thanks for the summary, glad to know its working. I guess the install was just in a weird state.
