### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by atmatthewat** [pothosware/homebrew-pothos#13]
[ 96%] Linking CXX executable ../bin/LimeSuiteGUI
cd /tmp/limesuite-20170910-30684-1l60re0/LimeSuite-17.09.0/builddir/src && /usr/local/Cellar/cmake/3.9.2/bin/cmake -E cmake_link_script CMakeFiles/LimeSuiteGUI.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/usr/local/include/wx-3.0 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/LimeSuiteGUI.dir/ADF4002/ADF4002_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlXBUF_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlRFE_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlCalibrations_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlTRF_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlCDS_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlLimeLightPAD_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlBIST_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/dlgViewIRAM.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_gui_utilities.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlSX_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlTBB_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_dlgVCOfrequencies.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlRBB_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlLDO_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlAFE_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlGains_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/CoefficientFileParser.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlRxTSP_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_mainPanel.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/pnlBoardControls.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/dlgViewSFR.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlCLKGEN_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlMCU_BD_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlBIAS_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_dlgGFIR_Coefficients.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlTxTSP_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlR3.cpp.o CMakeFiles/LimeSuiteGUI.dir/LMS_Programing/LMS_Programing_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/dlgConnectionSettings.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/pnlMiniLog.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/SPI_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/dlgFullMessageLog.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/dlgDeviceInfo.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/utilities_gui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7suiteAppFrame.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/lms7002m_novena_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/RFSpark/RFSpark_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/Si5351C/Si5351C_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7suiteApp_gui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7suiteApp.cpp.o CMakeFiles/LimeSuiteGUI.dir/FPGAcontrols_wxgui/FPGAcontrols_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/HPM7/HPM7_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/dlgAbout.cpp.o CMakeFiles/LimeSuiteGUI.dir/numericSlider/numericSlider.cpp.o CMakeFiles/LimeSuiteGUI.dir/myriad7/myriad7_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/fftviewer_wxgui/fftviewer_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/fftviewer_wxgui/fftviewer_frFFTviewer.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7suiteEvents/lms7suiteEvents.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlQSpark.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnluLimeSDR.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlUltimateEVB.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlBuffers.cpp.o CMakeFiles/LimeSuiteGUI.dir/kissFFT/kiss_fft.c.o CMakeFiles/LimeSuiteGUI.dir/windowFunction.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlLimeSDR.cpp.o  -o ../bin/LimeSuiteGUI -Wl,-rpath,/tmp/limesuite-20170910-30684-1l60re0/LimeSuite-17.09.0/builddir/src libLimeSuite.17.09.0.dylib oglGraph/liboglGraph.a -L/usr/local/lib -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL -lwx_osx_cocoau_richtext-3.0 -lwx_baseu_xml-3.0 -lwx_osx_cocoau_html-3.0 -lwx_osx_cocoau_xrc-3.0 -lwx_osx_cocoau_adv-3.0 -lwx_osx_cocoau_aui-3.0 -lwx_osx_cocoau_core-3.0 -lwx_baseu-3.0 -lwx_osx_cocoau_gl-3.0 /usr/local/opt/sqlite/lib/libsqlite3.dylib -framework GLUT -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL -lwx_osx_cocoau_richtext-3.0 -lwx_baseu_xml-3.0 -lwx_osx_cocoau_html-3.0 -lwx_osx_cocoau_xrc-3.0 -lwx_osx_cocoau_adv-3.0 -lwx_osx_cocoau_aui-3.0 -lwx_osx_cocoau_core-3.0 -lwx_baseu-3.0 -lwx_osx_cocoau_gl-3.0 
[ 96%] Built target LimeSuiteGUI
make: *** [all] Error 2

**Comment by guruofquality** [comment]
I have a feeling that there is a compiler difference where warnings gradually turn into errors. Can you rerun the command again with --verbose? The output should let me know how to patch LimeSuite.

Just in case we did already patch this, but it wasnt released yet, can you instread try to `brew install HEAD limesuite --verbose` That should build off the latest master branch. Thanks!

**Comment by atmatthewat** [comment]
[ 94%] Building CXX object src/CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlLimeSDR.cpp.o
cd /tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/builddir/src && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DLIME_DLL -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D__WXMAC__ -D__WXOSX_COCOA__ -D__WXOSX__ -D__unix__=1 -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/lms7002_wxgui -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/LMS_Programing -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/utilities_gui -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/RFSpark -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/FPGAcontrols_wxgui -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/numericSlider -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/myriad7 -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/fftviewer_wxgui -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/lms7suiteEvents -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/boards_wxgui -isystem /usr/local/lib/wx/include/osx_cocoa-unicode-3.0 -isystem /usr/local/include/wx-3.0 -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/API -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/GFIR -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/protocols -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/ConnectionRegistry -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/lms7002m_mcu -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/ADF4002 -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/Si5351C -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/lms7002m -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/LTEpackets -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/FPGA_common -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/external/cpp-feather-ini-parser -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/HPM7 -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/kissFFT -I/usr/local/opt/sqlite/include -I/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/oglGraph  -I/usr/local/include/wx-3.0 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12   -std=gnu++11 -o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlLimeSDR.cpp.o -c /tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/src/boards_wxgui/pnlLimeSDR.cpp
[ 95%] Linking CXX executable ../bin/LimeSuiteGUI
cd /tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/builddir/src && /usr/local/Cellar/cmake/3.9.2/bin/cmake -E cmake_link_script CMakeFiles/LimeSuiteGUI.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/usr/local/include/wx-3.0 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/LimeSuiteGUI.dir/ADF4002/ADF4002_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlXBUF_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlRFE_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlCalibrations_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlTRF_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlCDS_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlLimeLightPAD_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlBIST_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/dlgViewIRAM.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_gui_utilities.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlSX_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlTBB_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_dlgVCOfrequencies.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlRBB_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlLDO_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlAFE_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlGains_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/CoefficientFileParser.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlRxTSP_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_mainPanel.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/pnlBoardControls.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/dlgViewSFR.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlCLKGEN_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlMCU_BD_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlBIAS_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_dlgGFIR_Coefficients.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlTxTSP_view.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7002_wxgui/lms7002_pnlR3.cpp.o CMakeFiles/LimeSuiteGUI.dir/LMS_Programing/LMS_Programing_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/dlgConnectionSettings.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/pnlMiniLog.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/SPI_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/dlgFullMessageLog.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/dlgDeviceInfo.cpp.o CMakeFiles/LimeSuiteGUI.dir/utilities_gui/utilities_gui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7suiteAppFrame.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/lms7002m_novena_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/RFSpark/RFSpark_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/Si5351C/Si5351C_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7suiteApp_gui.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7suiteApp.cpp.o CMakeFiles/LimeSuiteGUI.dir/FPGAcontrols_wxgui/FPGAcontrols_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/HPM7/HPM7_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/dlgAbout.cpp.o CMakeFiles/LimeSuiteGUI.dir/numericSlider/numericSlider.cpp.o CMakeFiles/LimeSuiteGUI.dir/myriad7/myriad7_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/fftviewer_wxgui/fftviewer_wxgui.cpp.o CMakeFiles/LimeSuiteGUI.dir/fftviewer_wxgui/fftviewer_frFFTviewer.cpp.o CMakeFiles/LimeSuiteGUI.dir/lms7suiteEvents/lms7suiteEvents.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlQSpark.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnluLimeSDR.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlUltimateEVB.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlBuffers.cpp.o CMakeFiles/LimeSuiteGUI.dir/kissFFT/kiss_fft.c.o CMakeFiles/LimeSuiteGUI.dir/windowFunction.cpp.o CMakeFiles/LimeSuiteGUI.dir/boards_wxgui/pnlLimeSDR.cpp.o  -o ../bin/LimeSuiteGUI -Wl,-rpath,/tmp/limesuite-20170910-38681-1t7ul9r/LimeSuite-17.09.0/builddir/src libLimeSuite.17.09.0.dylib oglGraph/liboglGraph.a -L/usr/local/lib -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL -lwx_osx_cocoau_richtext-3.0 -lwx_baseu_xml-3.0 -lwx_osx_cocoau_html-3.0 -lwx_osx_cocoau_xrc-3.0 -lwx_osx_cocoau_adv-3.0 -lwx_osx_cocoau_aui-3.0 -lwx_osx_cocoau_core-3.0 -lwx_baseu-3.0 -lwx_osx_cocoau_gl-3.0 /usr/local/opt/sqlite/lib/libsqlite3.dylib -framework GLUT -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL -lwx_osx_cocoau_richtext-3.0 -lwx_baseu_xml-3.0 -lwx_osx_cocoau_html-3.0 -lwx_osx_cocoau_xrc-3.0 -lwx_osx_cocoau_adv-3.0 -lwx_osx_cocoau_aui-3.0 -lwx_osx_cocoau_core-3.0 -lwx_baseu-3.0 -lwx_osx_cocoau_gl-3.0 
[ 95%] Built target LimeSuiteGUI
make: *** [all] Error 2

==> Formula
Tap: pothosware/pothos
Path: /usr/local/Homebrew/Library/Taps/pothosware/homebrew-pothos/limesuite.rb
==> Configuration
HOMEBREW_VERSION: 1.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 751334a257d81851e68da7ab390982d4e9fdf909
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8889087e38b6e34910935a0da0819194b482b60f
Core tap last commit: 16 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/openssl:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_PATH: /usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/libusb/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/python/lib/pkgconfig:/usr/local/opt/soapysdr/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/cmake/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/libpng/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/wxmac/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl/bin:/usr/local/opt/python/bin:/usr/local/opt/soapysdr/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: pothosware/pothos/limesuite 17.09.0 did not build

**Comment by atmatthewat** [comment]
And building with --HEAD does work

**Comment by atmatthewat** [comment]
However once built, LimeUtil reports the only supported connection is "PCIEXillybus" and LimeUtil --find does not find any USB-attached hardware

**Comment by atmatthewat** [comment]
Fixed the available connection issue by having brew remove and reinstall libusb (why this was needed, I do not know)

**Comment by guruofquality** [comment]
Glad its working. No idea what was going on with libusb. Stale headers, development files? Maybe the first build attempt pulled in a system libusb, and after the reinstall it fixed any links for brew, and the rebuild used the proper brew version. if you have any ideas in the future, let us know for the sake of the wiki page. Best!
