### ISSUE TITLE
Error make

### ISSUE THREAD

**Issue by wizz777** [pothosware/homebrew-pothos#14]
LL -D_FILE_OFFSET_BITS=64 -D__WXMAC__ -D__WXOSX_COCOA__ -D__WXOSX__ -D__unix__=1 -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/API -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/GFIR -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/protocols -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/ConnectionRegistry -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/lms7002m_mcu -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/ADF4002 -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/Si5351C -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/lms7002m -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/LTEpackets -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/FPGA_common -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/external/cpp-feather-ini-parser -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/HPM7 -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/kissFFT -I/usr/local/opt/sqlite/include -I/usr/local/include/libusb-1.0 -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/lms7002_wxgui -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/LMS_Programing -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/utilities_gui -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/RFSpark -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/FPGAcontrols_wxgui -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/numericSlider -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/myriad7 -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/fftviewer_wxgui -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/lms7suiteEvents -I/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/boards_wxgui -isystem /usr/local/lib/wx/include/osx_cocoa-unicode-3.0 -isystem /usr/local/include/wx-3.0  -I/usr/local/include/wx-3.0 -DNDEBUG -fPIC   -std=gnu++11 -o CMakeFiles/LimeSuite.dir/FPGA_common/FPGA_common.cpp.o -c /tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/FPGA_common/FPGA_common.cpp
/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/API/lms7_api.cpp:736:14: error: ordered comparison between pointer and zero ('float_type *' (aka 'double *') and 'int')
    if (gain < 0)
        ~~~~ ^ ~
/tmp/limesuite-20170921-29120-1tmoyy5/LimeSuite-17.09.0/src/API/lms7_api.cpp:758:14: error: ordered comparison between pointer and zero ('unsigned int *' and 'int')
    if (gain < 0)
        ~~~~ ^ ~
2 errors generated.
make[2]: *** [src/CMakeFiles/LimeSuite.dir/API/lms7_api.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/LimeSuite.dir/all] Error 2
make: *** [all] Error 2

**Comment by wizz777** [comment]
and more

cd /tmp/pothos-20170921-30119-5kk0um/PothosCore-pothos-0.5.1/build/lib && /usr/local/Cellar/cmake/3.9.3/bin/cmake -E cmake_symlink_library libPothos.0.5.1.dylib libPothos.0.5.dylib libPothos.dylib
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.3/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.3/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

make[2]: *** [lib/libPothos.dylib] Abort trap: 6
make[2]: *** Deleting file `lib/libPothos.dylib'
make[1]: *** [lib/CMakeFiles/Pothos.dir/all] Error 2
make: *** [all] Error 2

**Comment by guruofquality** [comment]
For the limesuite error, you need to build brew with "HEAD" until there is a new release tag because it was fixed on master.

I'm not sure what to make of the utimensat message. So the cmake executable somehow uses this function, but its missing "Referenced from: /usr/local/Cellar/cmake/3.9.3/bin/cmake"?

I think its unrelated to anything actually in the brew recipes for pothos/soapysdr. Maybe reinstall cmake from brew?

**Comment by guruofquality** [comment]
updated limesuite.rb for the latest tag, I hope that includes the the compiler fix
