### ISSUE TITLE
Pothos Homebrew 0.6.0 incompatible with 0.5.1

### ISSUE THREAD

**Issue by bigbaldbob** [pothosware/homebrew-pothos#16]
While running:
brew reinstall --HEAD pothosgui
It fails with the following error:
(from: Bob   rjvnyc@gmail.com)

CMake Error at CMakeLists.txt:8 (find_package):
  Could not find a configuration file for package "Pothos" that is compatible
  with requested version "0.6.0".

  The following configuration files were considered but not accepted:

    /usr/local/share/cmake/Pothos/PothosConfig.cmake, version: 0.5.1-release
    /usr/local/opt/pothos/share/cmake/Pothos/PothosConfig.cmake, version: 0.5.1-release

-- Configuring incomplete, errors occurred!
See also "/tmp/pothosgui-20171202-935-u6cwtl/build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/pothosware/homebrew-pothos/issues

**Comment by guruofquality** [comment]
You are going to have to install either from release or from HEAD on all of the pothos* recipes. I'm working my way to a 0.6 release and tags this month: https://github.com/pothosware/PothosCore/issues/146

**Comment by guruofquality** [comment]
Also, new release tags are also available now, and wiki updated to match.
