### ISSUE TITLE
Tap seems to be broken

### ISSUE THREAD

**Issue by sludtke42** [pothosware/homebrew-pothos#18]
This is my first attempt with Homebrew (10.13):

> brew tap pothosware/homebrew-pothos

==> Tapping pothosware/pothos
Cloning into '/usr/local/Homebrew/Library/Taps/pothosware/homebrew-pothos'...
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 29 (delta 10), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (29/29), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pothosware/homebrew-pothos/pothossoapy.rb
No available formula with the name "pothossoapy" 
In formula file: /usr/local/Homebrew/Library/Taps/pothosware/homebrew-pothos/pothossoapy.rb
Expected to find class Pothossoapy, but only found: Pothossdr.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pothosware/homebrew-pothos/pothosflow.rb
No available formula with the name "pothosflow" 
In formula file: /usr/local/Homebrew/Library/Taps/pothosware/homebrew-pothos/pothosflow.rb
Expected to find class Pothosflow, but only found: Pothosgui.
Error: Cannot tap pothosware/pothos: invalid syntax in tap!

**Comment by guruofquality** [comment]
Sorry, I made a quick rename for the formula files after the release and forgot to test. I forgot to also rename the formula/class itself. Does it work now?

**Comment by sludtke42** [comment]
Yep, thanks for the quick reply!  Testing the install now.
--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu)
Baylor College of Medicine                             
sludtke@bcm.edu

**Comment by guruofquality** [comment]
thanks
