### ISSUE TITLE
pothosflow compile error

### ISSUE THREAD

**Issue by jhicks-camgian** [pothosware/homebrew-pothos#19]
XCode update today might be relevant?
Jerrys-Mac-mini:~ jhicks$ clang++ --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Compile error: 

Jerrys-Mac-mini:~ jhicks$ brew install pothosflow
==> Installing pothosflow from pothosware/pothos
==> Downloading https://github.com/pothosware/PothosFlow/archive/pothos-gui-0.5.1.tar.gz
Already downloaded: /Users/jhicks/Library/Caches/Homebrew/pothosflow-0.5.1.tar.gz
==> cmake .. -DBUNDLE_DESTINATION=. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/pothosflow/0.5.1 -DCMAKE_BUILD_TYPE=Rel
==> make install
Last 15 lines from /Users/jhicks/Library/Logs/Homebrew/pothosflow/02.make:
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DPOCO_NO_AUTOMATIC_LIBS -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/tmp/pothosflow-20171230-10425-1a062bu/PothosFlow-pothos-gui-0.5.1/build -I/tmp/pothosflow-20171230-10425-1a062bu/PothosFlow-pothos-gui-0.5.1 -I/tmp/pothosflow-20171230-10425-1a062bu/PothosFlow-pothos-gui-0.5.1/build/PothosGui_autogen/include -isystem /usr/local/include -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -I/tmp/pothosflow-20171230-10425-1a062bu/PothosFlow-pothos-gui-0.5.1/qtcolorpicker/src  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk   -fPIC -std=gnu++11 -o CMakeFiles/PothosGui.dir/AffinitySupport/AffinityZonesComboBox.cpp.o -c /tmp/pothosflow-20171230-10425-1a062bu/PothosFlow-pothos-gui-0.5.1/AffinitySupport/AffinityZonesComboBox.cpp
/tmp/pothosflow-20171230-10425-1a062bu/PothosFlow-pothos-gui-0.5.1/BlockTree/BlockCache.cpp:87:40: error: call to member function 'call' is ambiguous
            const auto json = DocUtils.call<std::string>("dumpJsonAt", path.toStdString());
                              ~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/local/include/Pothos/Proxy/ProxyImpl.hpp:77:19: note: candidate function [with ReturnType = std::__1::basic_string<char>, ArgsType = <std::__1::basic_string<char>>]
ReturnType Proxy::call(const std::string &name, ArgsType&&... args) const
                  ^
/usr/local/include/Pothos/Proxy/ProxyImpl.hpp:84:14: note: candidate function [with ArgsType = <std::__1::basic_string<char>>]
Proxy Proxy::call(const std::string &name, ArgsType&&... args) const
             ^
1 error generated.
make[2]: *** [CMakeFiles/PothosGui.dir/BlockTree/BlockCache.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/PothosGui.dir/all] Error 2
make: *** [all] Error 2

**Comment by guruofquality** [comment]
Looks like a problem with my formula updater script because I renamed project. I fixed it manually for now. Thanks for catching that.

**Comment by guruofquality** [comment]
Fixed my updated script too, and tested full compile.
