### ISSUE TITLE
Getting errors when doing brew upgrade

### ISSUE THREAD

**Issue by ulso** [pothosware/homebrew-pothos#2]
==> Upgrading pothosware/pothos/pothospython
==> Downloading https://github.com/pothosware/pothos-python/archive/pothos-pytho
Already downloaded: /Users/ulf/Library/Caches/Homebrew/pothospython-0.1.4.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
Last 15 lines from /Users/ulf/Library/Logs/Homebrew/pothospython/01.cmake:
-- PothosSerialization_VERSION: 0.2.0
-- PothosSerialization_INCLUDE_DIRS: /usr/local/include
-- PothosSerialization_LIBRARIES: /usr/local/lib/libPothosSerialization.dylib
dyld: Library not loaded: /usr/local/opt/poco/lib/libPocoUtil.42.dylib
  Referenced from: /usr/local/bin/PothosUtil
  Reason: image not found
/tmp/pothospython-20160705-18069-1jmnerb/pothos-python-pothos-python-0.1.4/build/PothosUtil.sh: line 4: 18152 Trace/BPT trap: 5       "/usr/local/bin/PothosUtil" $@
CMake Error at /usr/local/share/cmake/Pothos/PothosConfig.cmake:198 (message):
  PothosUtil execution test failed
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/pothospython-20160705-18069-1jmnerb/pothos-python-pothos-python-0.1.4/build/CMakeFiles/CMakeOutput.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/pothosware/homebrew-pothos/issues

**Comment by guruofquality** [comment]
> dyld: Library not loaded: /usr/local/opt/poco/lib/libPocoUtil.42.dylib
Referenced from: /usr/local/bin/PothosUtil
Reason: image not found

So PothosUtil is crashing, but I have never seen that error. It looks like it used poco libs from something other than homebrew (I dont think I have seen it in /usr/local/opt/). Perhaps poco in /usr/local/opt/ went away or changed, and now PothosUtil doesn’t know what to do and dies. You might try updating homebrew poco and just removing and reinstalling pothos packages.

**Comment by ulso** [comment]
Could it be that PothosUtil tries load libPocoUtil.42.dylib and explicitly that version?
I checked my /usr/local/lib for the Poco stuff an found only files with .43. in the file names, so there was a libPocoUtil.43.dylib.
There was also a libPocoUtil.dylib, so I guess Pothos should try to load that one?

**Comment by guruofquality** [comment]
> Could it be that PothosUtil tries load libPocoUtil.42.dylib and explicitly that version?

Yes, that probably the version it was built against. 

> I checked my /usr/local/lib for the Poco stuff an found only files with .43. in the file names, so there was a libPocoUtil.43.dylib.

Sounds like there was an upgrade. I'm still not sure about the /usr/local/opt/ but an important dependency library went away is my guess, so it needs a rebuild.

> There was also a libPocoUtil.dylib, so I guess Pothos should try to load that one?

Thats probably a symlink for development purposes, the actual file is the one with the soversion name built in. Technically one development symlink can exist with several different soversions lying around. Which each app looking at a different soversion of that library that it was compiled against at that time.

Anyway, if something got deleted in regards to poco and it was outside of homebrew I guess, so homebrew didnt know to rebuilt the software that depended on poco.

**Comment by ulso** [comment]
In the VERSION file for pothosware/poco it says 1.7.0
The current homebrew version of poco is 1.7.3
Woudn't it be a good idea to fork the newer version of poco into pothosware?

**Comment by guruofquality** [comment]
I just track the latest poco release branch as a submodule to build from in case the user does not have poco libraries. Pothos is compatible with Poco 1.5.2 and up I believe (if not 1.6 series for sure). Poco is pretty good about not breaking things, seems like most API and library additions are additive.

I recommend using whatever compatible version of Poco the build system offers, since they went through the trouble to figure out any build issues and packaging binaries for quick installation. And I'm not sure that I want to get into managing a custom poco recipe unless there is a need for it. Besides, cant you just build the head version of Poco to get the latest: ``brew install poco HEAD``?

**Comment by ulso** [comment]
Well, I already have the latest poco version installed. If I do `brew install poco --HEAD`, I get a warning message.
`Warning: poco-1.7.3 already installed`

I then tried `brew install -s pothospython`to build from sources. That didn't help either. It still complains about libPocoUtil.42.dylib not being found.

Finally by doing `brew uninstall pothos --force`
followed by `brew install pothos`I could successfully do `brew install pothospython`.

**Comment by guruofquality** [comment]
> Finally by doing brew uninstall pothos --force
followed by brew install pothosI could successfully do brew install pothospython.

FWIW, this was my first suggestion. :-) You might find that the other toolkits like _pothosgui_ have similar issues. Since I assume they were all compiled against a version of Poco that was removed. But glad its building now.
