### ISSUE TITLE
Update of the install instructions or issue on my install?

### ISSUE THREAD

**Issue by Toontje** [pothosware/homebrew-pothos#26]
tmachielsen@MyLaptop:~ $ brew install soapyaudio
Error: pothosware/pothos/soapyaudio is a head-only formula
Install with `brew install --HEAD pothosware/pothos/soapyaudio`

**Comment by guruofquality** [comment]
This project never had a release tag, i guess the wiki should have --HEAD

**Comment by guruofquality** [comment]
Actually, probably just better to make a release tag, obviously the brew formula will get updated https://github.com/pothosware/SoapyAudio/issues/12
