### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by Toontje** [pothosware/homebrew-pothos#27]
How can i remove this warning?

**Comment by guruofquality** [comment]
Its coming from qt. It might be that one of the images need some profile stripped https://wiki.archlinux.org/index.php/Libpng_errors Hopefully its from one of the images checked into PothosFlow repo. I cant do anything if it turns out to be some system icon

**Comment by guruofquality** [comment]
looks like this got resolved upstream in PothosFlow https://github.com/pothosware/PothosFlow/commit/f2a6d2c23db230e59013d9690fe60f3ffac48b62
