### ISSUE TITLE
--with-python

### ISSUE THREAD

**Issue by eblot** [pothosware/homebrew-pothos#28]
It seems there's a glitch in the `soapsdr` Homebrew recipe:

The recipe defines the following dependencies

    depends_on "python" => :optional
    depends_on "python3" => :recommended

but

    if build.with?("python2")
    # ...
    end
    if build.with?("python3")
    # ...
    end

I think there's a mismatch between `python`/`python2`.

Moreover, as Python 3 is now the default on Homebrew, _i.e._
  * python -> python3
  * python@2 -> python2
the option might be renamed as:

    depends_on "python2" => :optional
    depends_on "python" => :recommended

The same note would apply to `photospython`.

Finally, the doc states that if Python2 is selected, Python3 version should not be built, but as python3 is recommended and python2 optional, --with-python (v2) does not unselect --with-python (v3), and `photospython` ends up building for python v3 when v2 is selected.

I think v2/v3 test should be permuted.

https://gist.github.com/eblot/cbef897bdee98859c5cc14fc22a5e4d8

**Comment by guruofquality** [comment]
@eblot Looks like a good suggestion. Python has also been a moving target, I'm happy to take any advice here as to what looks the most homebrew like these days. Can you make a pull request with the purposed changes?
