### ISSUE TITLE
spuce build issue

### ISSUE THREAD

**Issue by eblot** [pothosware/homebrew-pothos#29]
With homebrew (macOS), `spuce` sometime fails to build - which in turn prevents from installating `pothoscomms` & `photosplotters`

It seems there is an issue with dependency management (which makes make to fail randomly depending on how many jobs are spawn at build), and the Homebrew recipe fails to define the QT5 dependency

See https://gist.github.com/eblot/0ad6aa436f00236ee0156adb3b4827cd

The `spuce` project seems to have stalled, so it is probably better to report this issue with `photos` which maintains its own recipe.

**Comment by guruofquality** [comment]
Hey @audiofilter good to hear from you, you had me worried

Can you update your spuce.rb? https://github.com/audiofilter/homebrew-spuc/blob/master/spuce.rb

* Can you copy this file https://github.com/pothosware/homebrew-pothos/blob/master/spuce.rb
* and apply this patch https://gist.github.com/eblot/0ad6aa436f00236ee0156adb3b4827cd

There were various build changes, mostly qt related, probably from homebrew being a moving target.

If you can update the recipe, I can switch back to using homebrew-spuc again.

**Comment by audiofilter** [comment]
OK, will do tonight

**Comment by audiofilter** [comment]
OK. Done, hope it works

**Comment by guruofquality** [comment]
Thanks! Should be resolved with commit https://github.com/pothosware/homebrew-pothos/commit/2ff7760772dff96f4a65ac1947df470b08281b8f

Using spuc brew tap now
