### ISSUE TITLE
PothosFlow:  dyld: lazy symbol binding failed: Symbol not found: 

### ISSUE THREAD

**Issue by zzdts** [pothosware/homebrew-pothos#35]
`
dyld: lazy symbol binding failed: Symbol not found: __ZN5boost16re_detail_10700027cpp_regex_traits_char_layerIcE4initEv
  Referenced from: /usr/local/opt/uhd/lib/libuhd.3.14.1.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
dyld: Symbol not found: __ZN5boost16re_detail_10700027cpp_regex_traits_char_layerIcE4initEv
  Referenced from: /usr/local/opt/uhd/lib/libuhd.3.14.1.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
PothosFlow.EnvironmentEval: zone[]: I/O error: RemoteProxyEnvironment::transact(): connection inactive - Remote environment  crashed
`

**Comment by guruofquality** [comment]
Looks like a compilation issue with libuhd. Perhaps it was linked against one version of libboost_regex from brew, but another version was maybe available in a commonly searched header directory. Thats my best guess. Double check the build environment for uhd and maybe clean and rebuild things.
