### ISSUE TITLE
soapyosmo install fails, missing boost::chrono lib

### ISSUE THREAD

**Issue by j-mckim** [pothosware/homebrew-pothos#36]
When the brew install reaches the "make install" step for the soapyosmo package, it fails. The linker diagnostic is:

Undefined symbols for architecture x86_64:
  "boost::chrono::steady_clock::now()", referenced from:
...

Searching for others who have seen this issue led to this link:

https://github.com/YuvalNirkin/face_swap/issues/9

And a solution that worked for me:

[CMakeLists-patch.txt](https://github.com/pothosware/homebrew-pothos/files/4150391/CMakeLists-patch.txt)

Probably not the fix most conformant to the style of this project; just to communicate the gist of the fix, which was adding boost's chrono as a required library.

**Comment by guruofquality** [comment]
I added chrono to master branch
