### ISSUE TITLE
pothos install on Mac OSX Catalina failed 

### ISSUE THREAD

**Issue by fcapozzi** [pothosware/homebrew-pothos#38]
The message reported is 

iMac-di-Fabio:~ fabiocapozzi$ brew install pothos
Updating Homebrew...
==> Installing pothos from pothosware/pothos
==> Downloading https://github.com/pothosware/PothosCore/archive/pothos-0.6.1.tar.gz
Already downloaded: /Users/fabiocapozzi/Library/Caches/Homebrew/downloads/3643acb550dd1b14ce913a36d15b92e81be83172959efb65683777b1a65f4a00--PothosCore-pothos-0.6.1.tar.gz
==> cmake .. -DPOTHOS_EXTVER=release -DPOTHOS_ROOT='/usr/local' -DENABLE_INTERNAL_POCO=OFF -DENABLE_INTERNAL_SPU
==> make install
Last 15 lines from /Users/fabiocapozzi/Library/Logs/Homebrew/pothos/02.make:
inline std::size_t hash(Int32 n)
                   ^
/usr/local/include/Poco/Hash.h:84:20: note: candidate function
inline std::size_t hash(UInt32 n)
                   ^
/usr/local/include/Poco/Hash.h:90:20: note: candidate function
inline std::size_t hash(Int64 n)
                   ^
/usr/local/include/Poco/Hash.h:96:20: note: candidate function
inline std::size_t hash(UInt64 n)
                   ^
1 error generated.
make[2]: *** [lib/CMakeFiles/Pothos.dir/Object/Convert.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/Pothos.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/pothosware/homebrew-pothos/issues

**Comment by guruofquality** [comment]
see https://github.com/pothosware/homebrew-pothos/issues/37

**Comment by guruofquality** [comment]
There is a new release tag with the poco fix
