### ISSUE TITLE
brew install soapybladerf fails

### ISSUE THREAD

**Issue by ericbieri** [pothosware/homebrew-pothos#39]
[soapy_install_error.txt](https://github.com/pothosware/homebrew-pothos/files/4605434/soapy_install_error.txt)
Hi,
Great Project! Unfortunately the brew installation fails on Mac OSX 10.15.4-x86_64
I tried "brew install  soapybladerf" first and then "brew install --HEAD soapybladerf". Output see below. For verbose output see attachement.

Thanks in advance!
Cheers Eric

erich@mac-eric-1 bin % brew install --HEAD soapybladerf
==> Installing soapybladerf from pothosware/pothos
==> Cloning https://github.com/pothosware/SoapyBladeRF.git
Cloning into '/Users/erich/Library/Caches/Homebrew/soapybladerf--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> cmake ..
==> make install
Last 15 lines from /Users/erich/Library/Logs/Homebrew/soapybladerf/02.make:
        struct 
/usr/local/include/libbladeRF.h:2733:15: note: struct 'bladerf_stream' is hidden by a non-type declaration of 'bladerf_stream' here
int CALL_CONV bladerf_stream(struct bladerf_stream *stream,
              ^
/tmp/soapybladerf-20200510-90436-1rd86i4/bladeRF_Settings.cpp:100:24: error: variable has incomplete type 'bladerf_stream'
        bladerf_serial serial;
                       ^
/usr/local/include/libbladeRF.h:2583:8: note: forward declaration of 'bladerf_stream'
struct bladerf_stream;
       ^
6 errors generated.
make[2]: *** [CMakeFiles/bladeRFSupport.dir/bladeRF_Settings.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/bladeRFSupport.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/pothosware/homebrew-pothos/issues

Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.

**Comment by guruofquality** [comment]
It looks like maybe a mismatch of libbladeRF.h API Can you install libbladerf with --head as well or maybe just update it to the latest release?

**Comment by sielicki** [comment]
I was able to replicate the issue on catalina; bumped libbladerf in homebrew-core [1] and the issue was resolved.

[1]: https://github.com/Homebrew/homebrew-core/commit/3da35b155b843b9589a5b916bbeeaeed0ca8323d

**Comment by ericbieri** [comment]
Thanks @guruofquality  & @sielicki! The installation of soapybladerf works now on mac osx catalina.
