### ISSUE TITLE
Issue brewing limesuite

### ISSUE THREAD

**Issue by digitalentropy** [pothosware/homebrew-pothos#4]
Running 10.11, removed all old copies of homebrew, macports, etc, still having difficulties compiling.  Thoughts?

`==> Cloning https://github.com/myriadrf/LimeSuite.git
Cloning into '/Users/boop/Library/Caches/Homebrew/limesuite--git'...
remote: Counting objects: 395, done.
remote: Compressing objects: 100% (374/374), done.
remote: Total 395 (delta 44), reused 193 (delta 6), pack-reused 0
Receiving objects: 100% (395/395), 6.92 MiB | 7.72 MiB/s, done.
Resolving deltas: 100% (44/44), done.
Checking connectivity... done.
==> Checking out branch master
==> cmake .. -DENABLE_STREAM=ON -DENABLE_LMS7_GUI=ON -DENABLE_NOVENARF7=OFF -DENABLE_SOAPY_LMS7=ON -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_F
==> make install
Last 15 lines from /Users/boop/Library/Logs/Homebrew/limesuite/02.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1069:5: note: '~__nat' has been explicitly marked deleted here
    ~__nat() = delete;
    ^
14 errors generated.
make[2]: *** [src/CMakeFiles/LimeSuite.dir/lms7002m_novena/StreamerNovena.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/LimeSuite.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Linking CXX static library liboglGraph.a
cd /tmp/limesuite-20160725-31184-1najlp6/builddir/src/oglGraph && /usr/local/Cellar/cmake/3.6.1/bin/cmake -P CMakeFiles/oglGraph.dir/cmake_clean_target.cmake
cd /tmp/limesuite-20160725-31184-1najlp6/builddir/src/oglGraph && /usr/local/Cellar/cmake/3.6.1/bin/cmake -E cmake_link_script CMakeFiles/oglGraph.dir/link.txt --verbose=1
/usr/bin/ar qc liboglGraph.a  CMakeFiles/oglGraph.dir/dlgMarkers.cpp.o CMakeFiles/oglGraph.dir/GLFont.cpp.o CMakeFiles/oglGraph.dir/OpenGLGraph.cpp.o CMakeFiles/oglGraph.dir/glew/glew.c.o
/usr/bin/ranlib liboglGraph.a
[  8%] Built target oglGraph
make: *** [all] Error 2`

**Comment by guruofquality** [comment]
I just built this outside of brew and I think it was missing string include. This should fix it: https://github.com/myriadrf/LimeSuite/commit/b6dd03a84ddf057a88958979ce5ffa0479aa1e95

**Comment by digitalentropy** [comment]
Thanks, appears to build cleanly now, but while running LimeUtil --find finds my LimeSDR fine, LimeSuiteCalibrate results in:

`Traceback (most recent call last):
  File "/usr/local/bin/LimeSuiteCalibrate", line 8, in <module>
    import SoapySDR
ImportError: No module named SoapySDR`

Should I open a new issue or am I simply using it wrong?

**Comment by digitalentropy** [comment]
Or perhaps I shouldn't be running that command manually. Reading through LimeSuite docs now. :-)

**Comment by guruofquality** [comment]
> Traceback (most recent call last): File "/usr/local/bin/LimeSuiteCalibrate", line 8, in <module> import SoapySDR ImportError: No module named SoapySDR

It probably means soapysdr.rb didnt install python bindings or put them in a location thats not in the default python path. I think that it does build python bindings by default, but im not sure about the pythonpath part. A quick check of ``brew ls soapysdr`` (I think) can confirm the location. and python -c ``import sys; print(sys.path)`` to see where python is searching.
