### ISSUE TITLE
pothos install on Mac OSX Catalina failed

### ISSUE THREAD

**Issue by albedo0367** [pothosware/homebrew-pothos#42]
OS X catalina 10.15.5
Xcode Version 11.6 (11E708)
Python 3.7

The message error reported is 

Pierres-MacBook-16:~ pvareill$ brew install limesuite
==> Installing limesuite from pothosware/pothos
==> Downloading https://github.com/pothosware/SoapySDR/archive/soapy-sdr-0.7.2.tar.gz
Already downloaded: /Users/pvareill/Library/Caches/Homebrew/downloads/72b545f299183367d5aab40ff270c5598407078ba7d5e2ec28e5d24f46e34a63--SoapySDR-soapy-sdr-0.7.2.tar.gz
==> Downloading https://github.com/myriadrf/LimeSuite/archive/v20.01.0.tar.gz
Already downloaded: /Users/pvareill/Library/Caches/Homebrew/downloads/1b961a9ae6c4a5a84f461850dda436a28b10d7e18c1d52169e0a23e5bf2bf04e--LimeSuite-20.01.0.tar.gz
==> Installing dependencies for pothosware/pothos/limesuite: soapysdr
==> Installing pothosware/pothos/limesuite dependency: soapysdr
==> cmake .. -DENABLE_PYTHON=OFF -DENABLE_PYTHON3=ON -DSOAPY_SDR_EXTVER=release -DSOAPY_SDR_ROOT='/usr/local'
==> make install
Last 15 lines from /Users/pvareill/Library/Logs/Homebrew/soapysdr/02.make:
      _wrap_SwigPyIterator_incr(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_decr(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator_next(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      ...
  "__Py_NotImplementedStruct", referenced from:
      _wrap_SwigPyIterator___eq__(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator___ne__(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator___add__(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      _wrap_SwigPyIterator___sub__(_object*, _object*) in SoapySDRPYTHON_wrap.cxx.o
      SwigPyObject_richcompare(SwigPyObject*, SwigPyObject*, int) in SoapySDRPYTHON_wrap.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [python3/_SoapySDR.so] Error 1
make[1]: *** [python3/CMakeFiles/_SoapySDR3.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/pothosware/homebrew-pothos/issues

**Comment by guruofquality** [comment]
I need to take a release, details here: https://github.com/pothosware/homebrew-pothos/issues/41

**Comment by guruofquality** [comment]
I added the flag: https://github.com/pothosware/homebrew-pothos/commit/b0e380b0c158745f96af2d2e5e1a4fa86fdaec8f
