### ISSUE TITLE
Error making pothosplotters on Catalina

### ISSUE THREAD

**Issue by CybSec113** [pothosware/homebrew-pothos#45]
I don't seem to get any errors making qwt independently.

brew install --HEAD pothosplotters 
  or
brew install pothosplotters

Last 15 lines from /Users//Library/Logs/Homebrew/pothosplotters/02.make:
class QPainterPath;
      ^
/tmp/pothosplotters-20200916-99647-3ihy9s/qwt6/src/qwt_compass_rose.cpp:187:26: error: variable has incomplete type 'QPainterPath'
            QPainterPath lightPath;
                         ^
/usr/local/opt/qt/include/QtGui/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
[ 10%] Building CXX object CMakeFiles/PothosQwt.dir/qwt6/src/qwt_date_scale_engine.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQWT_DLL -DQWT_MAKEDLL -I/tmp/pothosplotters-20200916-99647-3ihy9s/build -I/tmp/pothosplotters-20200916-99647-3ihy9s -I/tmp/pothosplotters-20200916-99647-3ihy9s/build/PothosQwt_autogen/include -I/tmp/pothosplotters-20200916-99647-3ihy9s/qwt6/src -I/tmp/pothosplotters-20200916-99647-3ihy9s/PlotterUtils -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtOpenGL.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -fPIC -std=gnu++11 -o CMakeFiles/PothosQwt.dir/qwt6/src/qwt_date_scale_engine.cpp.o -c /tmp/pothosplotters-20200916-99647-3ihy9s/qwt6/src/qwt_date_scale_engine.cpp
2 errors generated.
make[2]: *** [CMakeFiles/PothosQwt.dir/qwt6/src/qwt_compass_rose.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/PothosQwt.dir/all] Error 2
make: *** [all] Error 2

**Comment by guruofquality** [comment]
That looks like a newer qt release broke the qwt build and qwt needs a patch to include qpainter stuff now. So I might need to switch repos to get a newer qwt tag because the qwt mirror doesnt seem to be updated.

However, if you do install "qwtqt5" from homebrew, it should use that and not try to build the submodule.

`brew install --HEAD pothosplotters --verbose` would show cmake output if cmake found the qwt dev files or not

**Comment by CybSec113** [comment]
trouble with "brew install qwtqt5":

[brew.out.txt](https://github.com/pothosware/homebrew-pothos/files/5235041/brew.out.txt)

here's pothosplotters verbose:

[brew2.out.txt](https://github.com/pothosware/homebrew-pothos/files/5235051/brew2.out.txt)

Thanks!!

**Comment by guruofquality** [comment]
This should help it to use the official qwt package. I guess they switched over to qt5 at some point

https://github.com/pothosware/homebrew-pothos/commit/0753fc54b45d56a39b07bae67e3f95bf177320d4

**Comment by guruofquality** [comment]
Massive qt support update and tags this year
