### ISSUE TITLE
No 'make install' when trying to install soapyuhd on Catalina 10.15.7

### ISSUE THREAD

**Issue by sm3ulc** [pothosware/homebrew-pothos#46]
brew install soapyuhd
Updating Homebrew...
==> Installing soapyuhd from pothosware/pothos
==> Downloading https://github.com/pothosware/SoapyUHD/archive/soapy-uhd-0.4.1.tar.gz
Already downloaded: /Users/xxxxx/Library/Caches/Homebrew/downloads/49350b1f492715d569602b91a4b58233920a0a908c81c93a93a240fc9b1f458e--SoapyUHD-soapy-uhd-0.4.1.tar.gz
==> cmake .. -DUHD_ROOT='.'
==> make install
Last 15 lines from /Users/xxxxxLibrary/Logs/Homebrew/soapyuhd/02.make:
2020-10-15 12:50:03 +0200

make
install

make: *** No rule to make target `install'.  Stop.

**Comment by guruofquality** [comment]
The cmake configuration must have bugged out finding some dependency. You should build with --verbose to see if anything interesting shows up.

**Comment by blegal** [comment]
I got the same issue on an ARM M1 host. My issue comes from C++14 source codes. Indeed,
the compiler is setup for C++11 by default.

I modified the :

vim /opt/homebrew/Library/Taps/pothosware/homebrew-pothos/soapyuhd.rb

as follow:

args += %W[-DUHD_ROOT='.' -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-std=c++14"]

And now it works like a charm ;-)

**Comment by guruofquality** [comment]
I making the SoapyUHD project specify the c++14 flag: https://github.com/pothosware/SoapyUHD/commit/1f7b6fa245f782e5d18453f5cbc6d9f27e6b26df So a brew install for soapyuhd --head should also do it
