### ISSUE TITLE
pothosplotters should depend on pothoscomms

### ISSUE THREAD

**Issue by EvanKrall** [pothosware/homebrew-pothos#5]
I installed pothosplotters without installing pothoscomms, and whenever I add a plotter block, I get repeated errors of:

```
 -> {Proxy Exception Message: Plugin Registry Error: Pothos::PluginRegistry::get(/blocks/comms/wave_trigger): plugin path not found}
2016-11-29 17:35:47 PothosGui.BlockEval.guiEval: Periodogram0-Proxy Exception Message: Exception: ProxyBlockEval factory(/plotters/periodogram)
```

These errors go away after installing pothoscomms

**Comment by guruofquality** [comment]
Good catch. Fixed: https://github.com/pothosware/homebrew-pothos/commit/9cb523b86a0616f0f6a7b05e27740821d096bdbb
