### ISSUE TITLE
Error installing pothosgui 0.4.4 due to requesting libPocoUtil.47.dylib

### ISSUE THREAD

**Issue by threshold68** [pothosware/homebrew-pothos#9]
Installation of pothosgui 0.4.4. fails with the following error message:

Last 15 lines from ...../Library/Logs/Homebrew/pothosgui/01.cmake:
-- PothosSerialization_VERSION: 0.2.0
-- PothosSerialization_INCLUDE_DIRS: /usr/local/include
-- PothosSerialization_LIBRARIES: /usr/local/lib/libPothosSerialization.dylib
dyld: Library not loaded: /usr/local/opt/poco/lib/libPocoUtil.47.dylib
  Referenced from: /usr/local/bin/PothosUtil
  Reason: image not found
/tmp/pothosgui-20170407-82162-1ixgyxl/pothos-gui-pothos-gui-0.4.4/build/PothosUtil.sh: line 4: 82245 Abort trap: 6           "/usr/local/bin/PothosUtil" $@
CMake Error at /usr/local/share/cmake/Pothos/PothosConfig.cmake:211 (message):
  PothosUtil execution test failed
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)

poco is installed with homebrew and the installed version is  1.7.8_1.
Therfore libPocoUtil is installed and symlinked as  libPocoUtil.48.dylib and libPocoUtil.dylib.

BR/Harry

**Comment by guruofquality** [comment]
Sounds like an issue with the install of poco. Can you remove poco and reinstall, and `brew link poco` if necessary?

**Comment by threshold68** [comment]
Dear Josh,I think I'd tried that 
already before filing the bug report but I tried again, however the 
error still persisted.Finally, I got it solved by uninstalling 
pothos completely and reinstalling it again.Additionally, poco 
was also upgraded by homebrew (to poco 1.7.8p1) before reinstalling 
pothos.So, I am not quite sure whether reinstalling pothos or 
updating poco solved the problem...BR/Harald

   
   	Josh Blum        8. 
April 2017 um 00:14    Sounds like an issue with 
the install of poco. Can you remove poco and reinstall, and brew 
link poco if necessary?

—You

 are receiving this because you authored the thread.Reply to this 
email directly, view

 it on which pGitHub, or mute

 the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pothosware/homebrew-pothos","title":"pothosware/homebrew-pothos","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/pothosware/homebrew-pothos">"https://github.com/pothosware/homebrew-pothos"</a>}},

"updates":{"snippets":[{"icon":"PERSON","message":"@guruofquality in #9: Sounds like an issue with the install of poco. Can you remove poco and reinstall, and `brew link poco` if necessary?"}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/pothosware/homebrew-pothos/issues/9#issuecomment-292664662">"https://github.com/pothosware/homebrew-pothos/issues/9#issuecomment-292664662"</a>}}}
